name: 'first_project'
version: '1.0.0'
config-version: 2

profile: 'first_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  first_project:
    +database: "{{ env_var('DBT_TARGET_DATABASE', 'RAW') }}"

    staging:
      +database: "{{ env_var('DBT_STAGING_DATABASE', 'RAW') }}"
      +schema: TAXI
      +materialized: view
      taxi:
        +materialized: view

    intermediate:
      +database: "{{ env_var('DBT_INTERMEDIATE_DATABASE', 'INTERMEDIATE') }}"
      +schema: TAXI
      +materialized: view

